# Generated by Django 5.2 on 2025-05-24 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(editable=False, max_length=255)),
                (
                    "varsity_id",
                    models.CharField(
                        blank=True, editable=False, max_length=8, null=True
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        blank=True, editable=False, max_length=7, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                (
                    "payment_slip",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "student_status",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("improvement", "Improvement"),
                        ],
                        max_length=12,
                    ),
                ),
                ("courses", models.JSONField()),
                (
                    "hall_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Alaol Hall", "Alaol Hall"),
                            ("A. F. Rahman Hall", "A. F. Rahman Hall"),
                            ("Shahjalal Hall", "Shahjalal Hall"),
                            ("Suhrawardy Hall", "Suhrawardy Hall"),
                            ("Shah Amanat Hall", "Shah Amanat Hall"),
                            ("Shamsun Nahar Hall", "Shamsun Nahar Hall"),
                            ("Shaheed Abdur Rab Hall", "Shaheed Abdur Rab Hall"),
                            ("Pritilata Hall", "Pritilata Hall"),
                            (
                                "Deshnetri Begum Khaleda Zia Hall",
                                "Deshnetri Begum Khaleda Zia Hall",
                            ),
                            ("Masterda Surja Sen Hall", "Masterda Surja Sen Hall"),
                            (
                                "Shaheed Farhad Hossain Hall",
                                "Shaheed Farhad Hossain Hall",
                            ),
                            ("Bijoy 24 Hall", "Bijoy 24 Hall"),
                            ("Nawab Faizunnesa Hall", "Nawab Faizunnesa Hall"),
                            ("Atish Dipankar Hall", "Atish Dipankar Hall"),
                            (
                                "Shilpi Rashid Chowdhury Hostel",
                                "Shilpi Rashid Chowdhury Hostel",
                            ),
                        ],
                        help_text="Select your residential hall",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
