# Generated by Django 5.1.7 on 2025-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examregistration",
            name="payment_slip",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="examregistration",
            name="varsity_id",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
