# Generated by Django 5.1.7 on 2025-04-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_manager", "0002_alter_examregistration_payment_slip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examregistration",
            name="full_name",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="examregistration",
            name="session",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="examregistration",
            name="varsity_id",
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
    ]
